import { product } from "perfume";

export const DUMMY_DATA: product[] = [
  {
    imgUrl: "https://fimgs.net/mdimg/perfume/375x500.609.jpg",
    note1: "Castoreum",
    note2: "Oakmoss",
    note3: "Rose",
    perfumeBrand: { brandName: "Diptyque", korName: "딥디크" },
    perfumeId: 1025,
    perfumeName: "Kimonanthe",
    perfumeScore: 0,
  },
  {
    imgUrl: "https://fimgs.net/mdimg/perfume/375x500.609.jpg",
    note1: "Castoreum",
    note2: "Oakmoss",
    note3: "Rose",
    perfumeBrand: { brandName: "Diptyque", korName: "딥디크" },
    perfumeId: 1025,
    perfumeName: "Kimonanthe",
    perfumeScore: 0,
  },
  {
    imgUrl: "https://fimgs.net/mdimg/perfume/375x500.609.jpg",
    note1: "Castoreum",
    note2: "Oakmoss",
    note3: "Rose",
    perfumeBrand: { brandName: "Diptyque", korName: "딥디크" },
    perfumeId: 1025,
    perfumeName: "Kimonanthe",
    perfumeScore: 0,
  },
  {
    imgUrl: "https://fimgs.net/mdimg/perfume/375x500.609.jpg",
    note1: "Castoreum",
    note2: "Oakmoss",
    note3: "Rose",
    perfumeBrand: { brandName: "Diptyque", korName: "딥디크" },
    perfumeId: 1025,
    perfumeName: "Kimonanthe",
    perfumeScore: 0,
  },
  {
    imgUrl: "https://fimgs.net/mdimg/perfume/375x500.609.jpg",
    note1: "Castoreum",
    note2: "Oakmoss",
    note3: "Rose",
    perfumeBrand: { brandName: "Diptyque", korName: "딥디크" },
    perfumeId: 1025,
    perfumeName: "Kimonanthe",
    perfumeScore: 0,
  },
  {
    imgUrl: "https://fimgs.net/mdimg/perfume/375x500.609.jpg",
    note1: "Castoreum",
    note2: "Oakmoss",
    note3: "Rose",
    perfumeBrand: { brandName: "Diptyque", korName: "딥디크" },
    perfumeId: 1025,
    perfumeName: "Kimonanthe",
    perfumeScore: 0,
  },
  {
    imgUrl: "https://fimgs.net/mdimg/perfume/375x500.609.jpg",
    note1: "Castoreum",
    note2: "Oakmoss",
    note3: "Rose",
    perfumeBrand: { brandName: "Diptyque", korName: "딥디크" },
    perfumeId: 1025,
    perfumeName: "Kimonanthe",
    perfumeScore: 0,
  },
  {
    imgUrl: "https://fimgs.net/mdimg/perfume/375x500.609.jpg",
    note1: "Castoreum",
    note2: "Oakmoss",
    note3: "Rose",
    perfumeBrand: { brandName: "Diptyque", korName: "딥디크" },
    perfumeId: 1025,
    perfumeName: "Kimonanthe",
    perfumeScore: 0,
  },
  {
    imgUrl: "https://fimgs.net/mdimg/perfume/375x500.609.jpg",
    note1: "Castoreum",
    note2: "Oakmoss",
    note3: "Rose",
    perfumeBrand: { brandName: "Diptyque", korName: "딥디크" },
    perfumeId: 1025,
    perfumeName: "Kimonanthe",
    perfumeScore: 0,
  },
  {
    imgUrl: "https://fimgs.net/mdimg/perfume/375x500.609.jpg",
    note1: "Castoreum",
    note2: "Oakmoss",
    note3: "Rose",
    perfumeBrand: { brandName: "Diptyque", korName: "딥디크" },
    perfumeId: 1025,
    perfumeName: "Kimonanthe",
    perfumeScore: 0,
  },
];
