-- MySQL Script generated by MySQL Workbench
-- Mon Mar  7 17:59:37 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema s06p22d104
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema s06p22d104
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `s06p22d104` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ;
USE `s06p22d104` ;

-- -----------------------------------------------------
-- Table `s06p22d104`.`clothes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `s06p22d104`.`clothes`;
CREATE TABLE IF NOT EXISTS `s06p22d104`.`clothes` (
  `c_id` INT(11) NOT NULL AUTO_INCREMENT,
  `c_type` INT(11) NOT NULL,
  `c_url` VARCHAR(200) NOT NULL,
  `gender` INT(11) NOT NULL,
  `age` INT(11) NOT NULL,
  `season` INT(11) NOT NULL,
  `tpo` INT(11) NOT NULL,
  `mood` INT(11) NOT NULL,
  PRIMARY KEY (`c_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `s06p22d104`.`perfume`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `s06p22d104`.`perfume`;
CREATE TABLE IF NOT EXISTS `s06p22d104`.`perfume` (
  `p_id` INT(11) NOT NULL,
  `p_name` VARCHAR(45) NOT NULL,
  `p_score` FLOAT NOT NULL,
  `p_brand` VARCHAR(45) NOT NULL,
  `p_url` VARCHAR(45) NOT NULL,
  `gender` INT(11) NOT NULL,
  `age` INT(11) NOT NULL,
  `season` INT(11) NOT NULL,
  `tpo` INT(11) NOT NULL,
  `mood` INT(11) NOT NULL,
  `date` DATETIME(6) NOT NULL,
  PRIMARY KEY (`p_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `s06p22d104`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `s06p22d104`.`user`;
CREATE TABLE IF NOT EXISTS `s06p22d104`.`user` (
  `u_seq` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `u_id` VARCHAR(45) NOT NULL,
  `u_nickname` VARCHAR(45) NOT NULL,
  `u_pw` VARCHAR(45) NOT NULL,
  `u_email` VARCHAR(45) NOT NULL,
  `time` DATETIME(6) NOT NULL,
  `u_type` TINYINT NOT NULL DEFAULT FALSE,
  PRIMARY KEY (`u_seq`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `s06p22d104`.`likeperfume`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `s06p22d104`.`likeperfume`;
CREATE TABLE IF NOT EXISTS `s06p22d104`.`likeperfume` (
  `p_like` TINYINT(4) NOT NULL DEFAULT 0,
  `u_seq` BIGINT(20) NOT NULL,
  `p_id` INT(11) NOT NULL,
  CONSTRAINT `p_id_3`
    FOREIGN KEY (`p_id`)
    REFERENCES `s06p22d104`.`perfume` (`p_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `u_seq_5`
    FOREIGN KEY (`u_seq`)
    REFERENCES `s06p22d104`.`user` (`u_seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `s06p22d104`.`review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `s06p22d104`.`review`;
CREATE TABLE IF NOT EXISTS `s06p22d104`.`review` (
  `r_title` VARCHAR(45) NOT NULL,
  `r_content` VARCHAR(45) NOT NULL,
  `time` DATETIME(6) NOT NULL,
  `u_seq` BIGINT(20) NOT NULL,
  `p_id` INT(11) NOT NULL,
  CONSTRAINT `p_id_2`
    FOREIGN KEY (`p_id`)
    REFERENCES `s06p22d104`.`perfume` (`p_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `u_seq_4`
    FOREIGN KEY (`u_seq`)
    REFERENCES `s06p22d104`.`user` (`u_seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `s06p22d104`.`survey1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `s06p22d104`.`survey1`;
CREATE TABLE IF NOT EXISTS `s06p22d104`.`survey1` (
  `s_id` INT(11) NOT NULL AUTO_INCREMENT,
  `gender` INT(11) NOT NULL,
  `age` INT(11) NOT NULL,
  `season` INT(11) NOT NULL,
  `tpo` INT(11) NOT NULL,
  `mood` INT(11) NOT NULL,
  `time` DATETIME(6) NOT NULL,
  `s_title` VARCHAR(45) NOT NULL,
  `u_seq` BIGINT(20) NOT NULL,
  PRIMARY KEY (`s_id`),
  INDEX `u_seq_idx` (`u_seq` ASC) ,
  CONSTRAINT `u_seq`
    FOREIGN KEY (`u_seq`)
    REFERENCES `s06p22d104`.`user` (`u_seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `s06p22d104`.`survey2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `s06p22d104`.`survey2`;
CREATE TABLE IF NOT EXISTS `s06p22d104`.`survey2` (
  `s_id` INT(11) NOT NULL AUTO_INCREMENT,
  `time` DATETIME(6) NOT NULL,
  `s_title` VARCHAR(45) NOT NULL,
  `u_seq` BIGINT(20) NOT NULL,
  `p_id` INT(11) NOT NULL,
  PRIMARY KEY (`s_id`),
  CONSTRAINT `p_id`
    FOREIGN KEY (`p_id`)
    REFERENCES `s06p22d104`.`perfume` (`p_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `u_seq_2`
    FOREIGN KEY (`u_seq`)
    REFERENCES `s06p22d104`.`user` (`u_seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `s06p22d104`.`survey3`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `s06p22d104`.`survey3`;
CREATE TABLE IF NOT EXISTS `s06p22d104`.`survey3` (
  `s_id` INT(11) NOT NULL AUTO_INCREMENT,
  `time` DATETIME(6) NOT NULL,
  `s_title` VARCHAR(45) NOT NULL,
  `c_id` INT(11) NOT NULL,
  `u_seq` BIGINT(20) NOT NULL,
  PRIMARY KEY (`s_id`),
  CONSTRAINT `c_id`
    FOREIGN KEY (`c_id`)
    REFERENCES `s06p22d104`.`clothes` (`c_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `u_seq_3`
    FOREIGN KEY (`u_seq`)
    REFERENCES `s06p22d104`.`user` (`u_seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;